-- ========================== CUSTOMER CONSTRAINTS ==========================

ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_CREDIT_CARD FOREIGN KEY (cust_credit_card_no)  
REFERENCES CREDIT_CARD (credit_card_no);

-- ========================== TRANSACTIONS CONSTRAINTS ==========================

ALTER TABLE TRANSACTIONS
ADD CONSTRAINT FK_TRANSACTIONS_RESERVATION FOREIGN KEY (trans_res_id)  
REFERENCES RESERVATION (res_no);

-- ========================== EMPLOYEE CONSTRAINTS ==========================

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_LOCATION FOREIGN KEY (emp_loc_id)  
REFERENCES LOCATION (loc_id);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_EMPLOYEE FOREIGN KEY (super_id)  
REFERENCES EMPLOYEE (emp_id);

-- ========================== LOCATION CONSTRAINTS ==========================

ALTER TABLE LOCATION
ADD CONSTRAINT FK_LOCATION_EMPLOYEE FOREIGN KEY (loc_super_id)  
REFERENCES EMPLOYEE (emp_id);

-- ========================== RESERVATION CONSTRAINTS ==========================

ALTER TABLE RESERVATION

ADD CONSTRAINT FK_RESERVATION_EMPLOYEE FOREIGN KEY (res_emp_id)  
REFERENCES EMPLOYEE (emp_id),
CONSTRAINT FK_RESERVATION_CUSTOMER FOREIGN KEY (res_cust_id)  
	REFERENCES CUSTOMER (cust_id),
CONSTRAINT FK_RESERVATION_LOCATION FOREIGN KEY (res_loc_id)  
	REFERENCES LOCATION (loc_id),
CONSTRAINT FK_RESERVATION_ROOM FOREIGN KEY (res_room_no)  
	REFERENCES ROOM (room_no);


-- ========================== ROOM CONSTRAINTS ==========================

ALTER TABLE ROOM
ADD CONSTRAINT FK_ROOM_LOCATION FOREIGN KEY (room_loc)  
REFERENCES LOCATION (loc_id);

ALTER TABLE ROOM
ADD CONSTRAINT FK_ROOM_ROOM_TYPE FOREIGN KEY (room_type)  
REFERENCES ROOM_TYPE (type_code);

-- ========================== ROOM TYPE ==========================