CREATE TABLE ROOM (
    ROOM_NO             INT PRIMARY KEY,     
    ROOM_LOCATION       INT, --FOREIGN KEY REFERENCES LOCATION(LOC_ID),
    ROOM_TYPE           INT,
    ROOM_AVAILABLE      NVARCHAR(1)
);